### ISSUE TITLE
Newer version of Symphony

### ISSUE THREAD

**Issue by burdiyan** [allure-framework/allure-php-adapter-api#24]
Is it planning to update the Symphony dependency to a newer version? I'm trying to use Allure with Laravel 4 framework, and have collision with version of Symphony required by Laravel and Allure PHP adapter API.

Thanks.

**Comment by vania-pooh** [comment]
We do modifications when there's some demand. If you need this then please send PR with respective modifications to composer.json and let's discuss it with other contributors.

**Comment by burdiyan** [comment]
Did that. Thank you!
