### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Gorjunov** [allure-framework/allure-php-adapter-api#28]
There is impossible to use changes in master with `allure-phpunit` (allure-phpunit package requires version 1.1.0). Would be good to create new release and update version of `allure-framework/allure-php-api` in `allure-phpunit` package.

**Comment by vania-pooh** [comment]
https://github.com/allure-framework/allure-php-adapter-api/releases/tag/1.1.2
PHPUnit module does not need update.
